---
name: Build
on:
  push:
    tags:
    - "*"

jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      
    - name: Set up Golang
      uses: actions/setup-go@v1
      with:
        go-version: 1.13.x
        
    - name: Fetch Golang dependencies 
      run: |
        export GOPATH=$HOME/go
        export GOBIN=$GOPATH/bin
        mkdir -p $GOPATH/src $GOPATH/bin
        go get github.com/inconshreveable/mousetrap 
        go get github.com/konsorten/go-windows-terminal-sequences 
        go get
        
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v1
      with:
        version: v0.124.1
        args: release --rm-dist
        workdir: .
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}